Just check it runs for now

diff --git a/.github/workflows/k8ssandra-cloud-install-test.yml b/.github/workflows/k8ssandra-cloud-install-test.yml
--- a/.github/workflows/k8ssandra-cloud-install-test.yml
+++ b/.github/workflows/k8ssandra-cloud-install-test.yml
@@ -81,20 +81,21 @@ jobs:
         run: |
           kubectl wait pods --for=condition=Ready -n ${K8SSANDRA_NAMESPACE} --timeout=900s -l app.kubernetes.io/created-by=cass-operator
 
-      # - name: Confirm it registered against AxonOps SaaS
-      #   run: |
-      #     COUNT=$(curl -s -H "Authorization: Bearer ${AXON_API_TOKEN}" \
-      #       https://dash.axonopsdev.com/${AXON_AGENT_ORG}/api/v1/nodes/${AXON_AGENT_ORG}/cassandra/${AXON_CLUSTER_NAME} \
-      #       | jq '.[]' | grep host_id | wc -l)
-      #     if [ "$COUNT" -gt 0 ]; then
-      #       echo "Cassandra cluster registered with AxonOps SaaS successfully"
-      #     else
-      #       echo "Failed to confirm Cassandra cluster registration with AxonOps SaaS"
-      #       exit 1
-      #     fi
-      #   env:
-      #     AXON_API_TOKEN: ${{ secrets.AXON_API_TOKEN }}
-      #     AXON_CLUSTER_NAME: ${{ env.K8SSANDRA_CLUSTER_NAME }}
+      - name: Confirm it registered against AxonOps SaaS
+        continue-on-error: true
+        run: |
+          COUNT=$(curl -s -H "Authorization: Bearer ${AXON_API_TOKEN}" \
+            https://dash.axonopsdev.com/${AXON_AGENT_ORG}/api/v1/nodes/${AXON_AGENT_ORG}/cassandra/${AXON_CLUSTER_NAME} \
+            | jq '.[]' | grep host_id | wc -l)
+          if [ "$COUNT" -gt 0 ]; then
+            echo "Cassandra cluster registered with AxonOps SaaS successfully"
+          else
+            echo "Failed to confirm Cassandra cluster registration with AxonOps SaaS"
+            exit 1
+          fi
+        env:
+          AXON_API_TOKEN: ${{ secrets.AXON_API_TOKEN }}
+          AXON_CLUSTER_NAME: ${{ env.K8SSANDRA_CLUSTER_NAME }}
 
       - name: Cleanup
         if: always()
